""" Developer Recruitment status

Revision ID: fc00faeff10f
Revises: 89c3265cccbc
Create Date: 2020-12-20 22:25:25.371007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = 'fc00faeff10f'
down_revision = '89c3265cccbc'
branch_labels = None
depends_on = None


developer_recruitment_status = postgresql.ENUM(
    "in_progress",
    "rejected",
    name="recruitmentstatus"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    developer_recruitment_status.create(op.get_bind())
    op.add_column('developer', sa.Column('recruitment_status', sa.Enum('rejected', 'in_progress', name='recruitmentstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developer', 'recruitment_status')
    developer_recruitment_status.drop(op.get_bind())
    # ### end Alembic commands ###
